config/routes.rb
ShoppingCart::Engine.routes.draw do
  get "/" => "order_items#index"
  post "/update_all" => "order_items#update_all"
  delete "/empty" => "order_items#empty_cart"

  resources :orders
  resources :order_items  
  
  ShoppingCart.checkout_steps.each do |step|
    get "/checkout/#{step}" => "checkouts##{step}"
    post "/checkout/#{step}" => "checkouts##{step}_confirm"
  end
end

app/models/address.rb
class Address < ApplicationRecord
  validates :street, :zipcode, :city, :phone, :country, presence: true
end

app/models/address_form.rb
class AddressForm < Reform::Form
  property :firstname
  property :lastname
  property :street
  property :city
  property :country
  property :zipcode
  property :phone

  validates :firstname, :lastname, :street, :city, :country, :zipcode, :phone, presence: true
  validates :phone, numericality: true, length: { minimum: 10, maximum: 15 }
  validates :zipcode, format: { with: /\A\d{5}-\d{4}|\A\d{5}\z/ }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/country.rb
class Country < ApplicationRecord
  validates :name, presence: true, uniqueness: true
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  has_many :orders
  validates :number, :cvv, :expiration_month, :expiration_year, presence: true 
end

app/models/credit_card_form.rb
class CreditCardForm < Reform::Form
  property :cvv
  property :expiration_year
  property :expiration_month
  property :number
  validates :number, :cvv, :expiration_year, :expiration_month, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  include AASM

  belongs_to :credit_card
  belongs_to :billing_address, class_name: 'Address'
  belongs_to :shipping_address, class_name: 'Address'
  has_many :order_items

  after_initialize :init
  after_update :get_item_total
  after_update :get_order_total

  def init 
    self.item_total ||= 0
    self.shipping ||= 0
    self.discount ||= 0
    self.credit_card ||= CreditCard.new
    self.billing_address ||= Address.new
    self.shipping_address ||= Address.new
  end

  aasm column: :state do
    state :in_progress, initial: true
    state :in_queue
    state :in_delivery
    state :delivered
    state :canceled

    event :place_order do
      transitions to: :in_queue, from: :in_progress
    end

    event :ship do
      transitions to: :in_delivery, from: :in_queue
    end
    
    event :complete do
      transitions to: :delivered, from: :in_delivery
    end

    event :cancel do
      transitions to: :canceled, from: :in_queue
    end
  end

  def add_item(item_id, quantity)
    item = ShoppingCart.item_class.constantize.find_by(id: item_id)
    order_item = order_items.find_by(item_id: item_id)
    if order_item
      order_item.quantity += quantity
      order_item.save
    else
      order_items.create(price: item.price, quantity: quantity, item: item)
    end
    get_item_total
  end

  def get_item_total
    total = order_items.inject(0) { |sum, item| sum + item.price } - discount
    update_columns(item_total: total)
    total
  end

  def get_order_total
    total = item_total + shipping
    update_columns(order_total: total)
    total
  end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item, class_name: ShoppingCart.item_class
  validates :price, :quantity, presence: true

  after_commit :update_price

  scope :from_order, -> (id) { where(order_id: id) }

  def update_price
    total = item.price * quantity
    update_columns(price: total)
    total
  end

end

app/models/shopping_cart/application_record.rb
module ShoppingCart
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/controllers/shopping_cart/application_controller.rb
module ShoppingCart
  class ShoppingCart::ApplicationController < ActionController::Base
    protect_from_forgery with: :exception   
    add_flash_types :success, :warning, :danger, :info
    helper_method :current_order
    
    def current_order 
      @current_order = Order.find_by(id: session[:current_order_id])
      set_current_order
    end

    def set_current_order
      if @current_order.nil?
        @current_order = Order.create
        session[:current_order_id] = @current_order.id
      end 
      @current_order
    end
  end

end

app/controllers/shopping_cart/checkouts_controller.rb
module ShoppingCart
  class CheckoutsController < ShoppingCart::ApplicationController
    before_filter :set_order 
    before_filter :check_address, only: [:payment, :confirm]
    before_filter :check_card, only: [:confirm]

    def address
      redirect_to '/cart', danger: "Cart is empty!" if @order.order_items.empty?   
      @countries = Country.pluck(:name)
      @address_form = AddressForm.new(Address.new)
    end

    def address_confirm
      @billing_address = Address.create(billing_address_params)
      @shipping_address = Address.create(shipping_address_params)

      if params[:use_billing]
        @order.update(billing_address: @billing_address, shipping_address: @billing_address)
      else
        @order.update(billing_address: @billing_address, shipping_address: @shipping_address)
      end

      if forms_valid?
        redirect_to next_after("address")
      else
        redirect_to cart.checkout_address_path
      end
      
    end

    def delivery_confirm
      @order.update(shipping: params[:shipping_price])
      redirect_to next_after("delivery")
    end

    def payment
      @credit_card_form = CreditCardForm.new(CreditCard.new)
    end

    def payment_confirm
      @credit_card_form = CreditCardForm.new(CreditCard.new)
      @credit_card = CreditCard.create(credit_card_params)
      @order.update(credit_card: @credit_card)

      if @credit_card_form.validate(credit_card_params)
        redirect_to next_after("payment")
      else
        redirect_to cart.checkout_payment_path
      end
    end

    def confirm
      @billing_address = @order.billing_address
      @shipping_address = @order.shipping_address
      @credit_card =  @order.credit_card
    end

    def complete
      @billing_address = @order.billing_address
      @shipping_address = @order.shipping_address
      @credit_card = @order.credit_card
      session[:order_id] = nil
      @order.place_order! 
    end

    private 
      def set_order 
        @order = current_order
      end

      def billing_address_params
        params.require(:billing_address).permit(:firstname, :lastname, :street, :city, :country, :zipcode, :phone)
      end

      def shipping_address_params
        params.require(:shipping_address).permit(:firstname, :lastname, :street, :city, :country, :zipcode, :phone)
      end

      def credit_card_params 
        params.require(:credit_card).permit(:number, :cvv, :expiration_year, :expiration_month)
      end

      def check_address
        redirect_to checkout_address_path unless current_order.billing_address && current_order.shipping_address 
      end

      def check_card 
        redirect_to checkout_payment_path unless current_order.credit_card
      end

      def forms_valid? 
        @address_form = AddressForm.new(Address.new)
        if params[:use_billing]
          @address_form.validate(billing_address_params)
        else 
          @address_form.validate(billing_address_params) && @address_form.validate(shipping_address_params)
        end
      end

      def next_after(current_step)
        index = ShoppingCart.checkout_steps.index(current_step) + 1
        @next_step = ShoppingCart.checkout_steps[index]
        return "/cart/checkout/#{@next_step}"
      end

      def next_step
        return next_after(action_name)
      end

  end
end

app/controllers/shopping_cart/order_items_controller.rb
module ShoppingCart  
  class OrderItemsController < ShoppingCart::ApplicationController
    before_filter :get_order, only: [:index, :create, :update_all]

    def index
      @order_items = @order.order_items
    end

    def create   
      @order.add_item(params[:order_item][:item_id], params[:order_item][:quantity].to_i)
      redirect_to cart.order_items_path
    end

    def destroy
      @order_item = current_order.order_items.find_by(id: params[:id])
      @order_item.delete
      current_order.get_item_total
      redirect_to cart.order_items_path
    end

    def empty_cart
      OrderItem.from_order(current_order.id).delete_all
      current_order.get_item_total
      redirect_to cart.order_items_path
    end

    def update_all
      return if @order.order_items.empty?
      params[:quantity].each do |item_id, quantity|
        @order.order_items.find_by_id(item_id).update(:quantity => quantity)
      end
      current_order.get_item_total
      redirect_to cart.order_items_path
    end

    private 
      def get_order
        @order = current_order
      end

  end
end

app/views/shopping_cart/checkouts/_address_form.html.erb
<br>
<%= f.text_field :firstname, placeholder: 'Firstname' %>
<br>
<%= f.text_field :lastname, placeholder: 'Lastname' %>
<br>
<%= f.text_field :street, placeholder: 'Street' %>
<br>
<%= f.text_field :city, placeholder: 'City' %>
<br>
<%= f.select :country, @countries %>
<br>
<%= f.text_field :zipcode, placeholder: "Zip" %>
<br>
<%= f.telephone_field :phone, placeholder: 'Phone' %>
<br>

app/views/shopping_cart/checkouts/_order_table.html.erb
<table class="table order-table">
  <th>Item</th>
  <th>Price</th>
  <th>Quantity</th>
  <th>Total</th>

  <% @order.order_items.each do |order_item| %>
    <tr>
      <td>
        <table>
          <tr>
            <td>
              <h4>
                <%= order_item.item.title %>
              </h4>
              <p>
                <%= order_item.item.description %>
              </p>
            </td>
          </tr>
        </table>
      </td>
      <td>
        <h4>
          <%= number_to_currency(order_item.item.price) %>
        </h4>
      </td>
      <td>
        <h4>
          <%= order_item.quantity %>
        </h4>
      </td>
      <td>
        <h4>
          <%= number_to_currency(order_item.price) %>
        </h4>
      </td>
    </tr>
  <% end %>
</table>
<div class="sub-total">
  <p>
    <%= "Item total: #{number_to_currency(@order.item_total)}"  %>
  </p>
  <p>
    <%= "Shipping: #{number_to_currency(@order.shipping)}" %>
  </p>
</div>
<div class="order-total">
  <p>
    <%= "Total: #{number_to_currency(@order.order_total)}" %>
  </p>
</div>

app/views/shopping_cart/checkouts/address.html.erb
<div class="wrapper">
  <div class="row">
    <div class="col-md-2">
      <h3>Checkout</h3>
    </div>
    <div class="col-md-10">
      <ul class="nav nav-pills">
        <li class="active" role="presentation">
          <a>Address</a>
        </li>
        <li class="disabled" role="presentation">
          <a>Delivery</a>
        </li>
        <li class="disabled" role="presentation">
          <a>Payment</a>
        </li>
        <li class="disabled" role="presentation">
          <a>Confirm</a>
        </li>
        <li class="disabled" role="presentation">
          <a>Complete</a>
        </li>
      </ul>
    </div>
  </div>
  <div class="row">
    <div class="address-form">
      <%= form_tag "/cart/checkout/address", method: 'post' do %>
        <div class="col-md-4">
          <h4> Billing address</h4>

          <%= fields_for :billing_address do |f| %>
            <%= render 'address_form', f: f %>
          <% end %>
        </div>
        <div class="col-md-4">
          <h4>Shipping address</h4>

          <%= check_box_tag :use_billing, 1, true %>
          <label>Use billing address</label>
          <%= fields_for :shipping_address do |f| %>
            <%= render 'address_form', f: f %>
          <% end %>
        </div>
        <div class="col-md-4">
          <h4>Order summary</h4>

          <div class="total">
            <%= "Total: #{number_to_currency(@order.item_total)}"   %>
          </div>
        </div>
        <div class="col-md-12">
          <button class="btn btn-default">Save</button>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shopping_cart/checkouts/complete.html.erb
<div class="wrapper">
  <h3>
    <%= "Order #{@order.id}" %>
  </h3>
  <div class="confirm">
    <div class="row">
      <div class="col-md-3">
        <table>
          <b>Shipping address</b>
          <tr>
            <td>
              <%= "#{@shipping_address.firstname} #{@shipping_address.lastname}" %>
            </td>
          </tr>
          <tr>
            <td>
              <%= @shipping_address.street %>
            </td>
          </tr>
          <tr>
            <td>
              <%= @shipping_address.city %>
            </td>
          </tr>
          <tr>
            <td>
              <%= @shipping_address.country %>
            </td>
          </tr>
          <tr>
            <td>
              <%= "Phone #{@shipping_address.phone}" %>
            </td>
          </tr>
        </table>
      </div>
      <div class="col-md-3">
        <table>
          <b>Billing address</b>
          <tr>
            <td>
              <%= "#{@billing_address.firstname} #{@billing_address.lastname}" %>
            </td>
          </tr>
          <tr>
            <td>
              <%= @billing_address.street %>
            </td>
          </tr>
          <tr>
            <td>
              <%= @billing_address.city %>
            </td>
          </tr>
          <tr>
            <td>
              <%= @billing_address.country %>
            </td>
          </tr>
          <tr>
            <td>
              <%= "Phone #{@billing_address.phone}" %>
            </td>
          </tr>
        </table>
      </div>
      <div class="col-md-3">
        <table>
          <b>Shipment</b>
          <tr>
            <td>
              <% case @order.shipping %>
                <% when 5 %>
                  <%= "UPS Ground" %>
                <% when 10 %>
                  <%= "UPS Two Day" %>
                <% when 15 %>
                  <%= "Ups One Day" %>
              <% end %>
            </td>
          </tr>
        </table>
      </div>
      <div class="col-md-3">
        <table>
          <b>Payment info</b>
          <tr>
            <td>
              <%= @credit_card.cvv %>
            </td>
          </tr>
          <tr>
            <td>
              <%= "#{@credit_card.expiration_month} / #{@credit_card.expiration_year}" %>
            </td>
          </tr>
        </table>
      </div>
    </div>
    <%= render "order_table" %>
    <a class="btn btn-default" href="/">Back to store</a>
  </div>
</div>  

app/views/shopping_cart/checkouts/confirm.html.erb
<div class="wrapper">
  <div class="row">
    <div class="col-md-2">
      <h3>
        Checkout
      </h3>
    </div>
    <div class="col-md-10">
      <ul class="nav nav-pills">
        <li role="presentation">
          <a href="<%= cart.checkout_address_path %>">
            Address
          </a>
        </li>
        <li role="presentation">
          <a href="<%= cart.checkout_delivery_path %>">
            Delivery
          </a>
        </li>
        <li role="presentation">
          <a href="<%= cart.checkout_payment_path %>">
            Payment
          </a>
        </li>
        <li class="active" role="presentation">
          <a>
            Confirm
          </a>
        </li>
        <li class="disabled" role="presentation">
          <a>
            Complete
          </a>
        </li>
      </ul>
    </div>
  </div>
  <h3>
    Confirm
  </h3>
  <div class="confirm">
    <div class="row">
      <div class="col-md-3">
        <table>
          <b>
            Shipping
          </b>
          <a href="<%= cart.checkout_address_path %>">(edit)</a>
          <tr>
            <td>
              <%= "#{@shipping_address.firstname} #{@shipping_address.lastname}" %>
            </td>
          </tr>
          <tr>
            <td>
              <%= @shipping_address.street %>
            </td>
          </tr>
          <tr>
            <td>
              <%= @shipping_address.city %>
            </td>
          </tr>
          <tr>
            <td>
              <%= @shipping_address.country %>
            </td>
          </tr>
          <tr>
            <td>
              <%= "Phone #{@shipping_address.phone}" %>
            </td>
          </tr>
        </table>
      </div>
      <div class="col-md-3">
        <table>
          <b>
            Billing
          </b>
          <a href="<%= cart.checkout_address_path %>">(edit)</a>
          <tr>
            <td>
              <%= "#{@shipping_address.firstname} #{@shipping_address.lastname}" %>
            </td>
          </tr>
          <tr>
            <td>
              <%= @billing_address.street %>
            </td>
          </tr>
          <tr>
            <td>
              <%= @billing_address.city %>
            </td>
          </tr>
          <tr>
            <td>
              <%= @billing_address.country %>
            </td>
          </tr>
          <tr>
            <td>
              <%= "Phone #{@billing_address.phone}" %>
            </td>
          </tr>
        </table>
      </div>
      <div class="col-md-3">
        <table>
          <b>
            <%= t('text.shipment') %>
          </b>
          <a href="<%= cart.checkout_delivery_path %>">(edit)</a>
          <tr>
            <td>
              <% case @order.shipping %>
                <% when 5 %>
                  <%= "UPS Ground" %>
                <% when 10 %>
                  <%= "UPS Two Day" %>
                <% when 15 %>
                  <%= "Ups One Day" %>
              <% end %>
            </td>
          </tr>
        </table>
      </div>
      <div class="col-md-3">
        <table>
          <b>
            Payment
          </b>
          <a href="<%= cart.checkout_payment_path %>">(edit)</a>
          <tr>
            <td>
              <%= @credit_card.cvv %>
            </td>
          </tr>
          <tr>
            <td>
              <%= "#{@credit_card.expiration_month} / #{@credit_card.expiration_year}" %>
            </td>
          </tr>
        </table>
      </div>
    </div>
    <%= render "order_table" %>
    <%= link_to "Place order", cart.checkout_complete_path, class: "btn btn-default" %>
  </div>
</div>

app/views/shopping_cart/checkouts/delivery.html.erb
<div class="wrapper">
  <div class="row">
    <div class="col-md-2">
      <h3>
        Checkout
      </h3>
    </div>
    <div class="col-md-10">
      <ul class="nav nav-pills">
        <li role="presentation">
          <a href="<%= cart.checkout_address_path %>">
            Address
          </a>
        </li>
        <li class="active" role="presentation">
          <a>
            Delivery
          </a>
        </li>
        <li class="disabled" role="presentation">
          <a>
            Payment
          </a>
        </li>
        <li class="disabled" role="presentation">
          <a>
            Confirm
          </a>
        </li>
        <li class="disabled" role="presentation">
          <a>
            Complete
          </a>
        </li>
      </ul>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8">
      <div class="delivery-form">
        <%= form_tag cart.checkout_delivery_path, method: "post" do %>
          <%= radio_button_tag :shipping_price, 5, active: true %>
          <%= label :shipping_price, 'UPS Ground +$5.00' %>
          <br/>
          <%= radio_button_tag :shipping_price, 10 %>
          <%= label :shipping_price, 'UPS Two Day +$10.00' %>
          <br/>
          <%= radio_button_tag :shipping_price, 15 %>
          <%= label :shipping_price, 'UPS One Day +$15.00' %>
          <br/>
          <button class="btn btn-default">Save</button>
        <% end %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="order-summary">
        <h2>
          Summary
        </h2>
        <table>
          <tr>
            <td>
              Item total
            </td>
            <td>
              <%= number_to_currency(@order.item_total) %>
            </td>
          </tr>
          <tr>
            <td>
              Shipping
            </td>
            <td>
              <%= number_to_currency(@order.shipping) %>
            </td>
          </tr>
          <tr>
            <td>
              Total
            </td>
            <td>
              <%= number_to_currency(@order.order_total) %>
            </td>
          </tr>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/shopping_cart/checkouts/payment.html.erb
<div class="wrapper">
  <div class="row">
    <div class="col-md-2">
      <h3>Checkout</h3>
    </div>
    <div class="col-md-10">
      <ul class="nav nav-pills">
        <li role="presentation">
          <a href="<%= cart.checkout_address_path %>">
            Address
          </a>
        </li>
        <li role="presentation">
          <a href="<%= cart.checkout_delivery_path %>">
            Delivery
          </a>
        </li>
        <li class="active" role="presentation">
          <a>
            Payment
          </a>
        </li>
        <li class="disabled" role="presentation">
          <a>
            Confirm
          </a>
        </li>
        <li class="disabled" role="presentation">
          <a>
            Complete
          </a>
        </li>
      </ul>
    </div>
  </div>
  <div class="payment-form">
    <div class="row">
      <div class="col-md-8">
        <h3>
          Credit card
        </h3>
        <%= form_for @credit_card_form, url: "/cart/checkout/payment" do |f| %>
          <%= f.text_field :number, placeholder: 'Card number' %>
          <p>Expiration date:</p>
          <%= f.select :expiration_month, Date::MONTHNAMES[1..12] %>
          <br>
          <%= f.select :expiration_year, Time.now.year.. 8.years.from_now.year %>
          <br>
          <%= f.text_field :cvv, placeholder: 'Card code'  %>
          <br>
          <button class="btn btn-default">Save</button>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shopping_cart/layouts/shopping_cart/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shopping cart</title>
  <%= stylesheet_link_tag    "shopping_cart/application", media: "all" %>
  <%= javascript_include_tag "shopping_cart/application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>

</body>
</html>

app/views/shopping_cart/order_items/_order_item.html.erb
<tr>
  <td>
    <table>
      <tr>
        <td>
          <h4><%= order_item.item.title %></h4>
          <p><%= order_item.item.description %></p>
        </td>
      </tr>
    </table>
  </td>
  <td>
    <h4>
      <%= number_to_currency(order_item.item.price) %>
    </h4>
  </td>
  <td>
    <%= number_field_tag('quantity['+order_item.id.to_s+']', order_item.quantity, {min: 1, }) %>
  </td>
  <td>
    <h4>
      <%= number_to_currency(order_item.price) %>
    </h4>
  </td>
  <td>
    <%= link_to "Remove", order_item_path(order_item), method: :delete %>
  </td>
</tr>

app/views/shopping_cart/order_items/_sub_total.html.erb
<%= "Discount: #{number_to_currency(@order.discount)}" %>
<br>
<%= "Total:    #{number_to_currency(@order.item_total)}" %>
<br>

app/views/shopping_cart/order_items/index.html.erb
<%= form_tag("/cart/update_all", controller: 'order_items', action: :update_all, method: :post) do %>
  <table class="table">
    <th>Item</th>
    <th>Price</th>
    <th>Quantity</th>
    <th>Total</th>
    <th></th>
    <% @order_items.each do |order_item| %>
      <%= render 'order_item', order_item: order_item %>
    <% end %>
  </table>
  
  <%= render('sub_total') %>
  
  <%= button_to "Update", cart.update_all_path, class: "btn btn-default" %>
  <%= button_to "Empty cart", "/cart/empty", method: "delete", class: "btn btn-default" %>
  <%= link_to "Checkout", "/cart/checkout/address", class: "btn btn-primary"%>
  
<% end %>

app/views/shopping_cart/partials/_notice.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key.to_s == 'notice' ? 'success' : 'danger' %>">
    <button aria-hidden="true" class="close" data-dismiss="alert" type="button">&times;</button>
    <%= content_tag :div, value, :id => "flash_#{key}" %>
  </div>
<% end %>